name: Run Test

on: [push, pull_request]

jobs:
  native:
    name: Build for native

    strategy:
      matrix:
        version: [4.10.x, 4.12.x]
        system: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.system }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install esy
        run: npm install -g esy

      - name: Create esy wrapper
        run: |
          echo '{
            "source": "./package.json",
            "override": {
              "dependencies": {
                "ocaml": "'${{ matrix.version }}'"
              }
            }
          }' > override.json

      - uses: esy/github-action@master
        with:
          manifest: override.json
          cache-key: ${{ hashFiles('esy.lock/index.json') }}

      - name: Test
        run: esy @override test
