name: Run Test

on: [push, pull_request]

jobs:
  native:
    name: Build for native

    strategy:
      matrix:
        system: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.system }}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install esy
        run: npm install -g esy

      - uses: esy/github-action@master
        with:
          cache-key: ${{ hashFiles('esy.lock/index.json') }}

      - name: Test
        run: esy test
